### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by at-vudang95** [at-vudang/Project-Sem-4-Foot-Market#12]

**Comment by at-vudang95** [comment]
![ERD.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596ecacf11f7b9001f9d94f9/125516c66e82c728ace21e0d46cda6be61cec1b99de6b546a749b2ce6b137e2b2d5df47875d3b27ebe1278515f5d18fd49090e46aeeb9539e4e76224d50152a7842f4d7ed43e10a6b9871fbd04b327894d85b4bb8e5e8d.png)

**Comment by at-TuLe** [comment]
chưa thấy chổ mô bất hợp lý.. còn thiếu thì chưa tìm ra
